use ft_sys::FT_Face;

/* automatically generated by rust-bindgen */

extern "C" {
    pub fn hb_ft_face_create(ft_face: FT_Face, destroy: ::hb_destroy_func_t)
     -> *mut ::hb_face_t;
    pub fn hb_ft_face_create_cached(ft_face: FT_Face) -> *mut ::hb_face_t;
    pub fn hb_ft_face_create_referenced(ft_face: FT_Face) -> *mut ::hb_face_t;
    pub fn hb_ft_font_create(ft_face: FT_Face, destroy: ::hb_destroy_func_t)
     -> *mut ::hb_font_t;
    pub fn hb_ft_font_create_referenced(ft_face: FT_Face) -> *mut ::hb_font_t;
    pub fn hb_ft_font_set_funcs(font: *mut ::hb_font_t);
    pub fn hb_ft_font_get_face(font: *mut ::hb_font_t) -> FT_Face;
}
